main_config:
  log_level: INFO
  path_log: "submitter.log"

step:
  translate:
    - KubernetesAdaptor
    - OccopusAdaptor
    - PkAdaptor
  execute:
    - OccopusAdaptor
    - KubernetesAdaptor
    - PkAdaptor
  update:
    - OccopusAdaptor
    - KubernetesAdaptor
    - PkAdaptor
  undeploy:
    - PkAdaptor
    - KubernetesAdaptor
    - OccopusAdaptor
  cleanup:
    - KubernetesAdaptor
    - OccopusAdaptor
    - PkAdaptor

adaptor_config:
 KubernetesAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   endoint: "endpoint"
   volume: "./files/output_configs/"


 OccopusAdaptor:
   types:
     - "tosca.nodes.MiCADO.Occopus.*"
   endoint: "endpoint"
   volume: "./files/output_configs/"


 PkAdaptor:
   types:
     - "tosca.policies.Scaling.MiCADO"
   endpoint: "policykeeper:12345"
   volume: "./files/output_configs/"